import mongoose, { Schema, Document } from "mongoose";

/**
 * Course model (revamp)
 *
 * Target structure:
 * {
 *   name,
 *   code,
 *   courseID,
 *   department: ObjectId (Department),
 *   unit: ObjectId (Unit),
 *   lecturer: [ObjectId],
 *   isActive,
 *   studentClasses: [{ classID, students: [ObjectId] }],
 *   academicYear: ObjectId,
 *   subjects: [{ name, code, subjectID, lecturer: [ObjectId], isActive, students: [ObjectId] }]
 * }
 */

export interface IStudentClassMembership {
  classID: mongoose.Types.ObjectId;
  students: mongoose.Types.ObjectId[];
}

export interface ICourseSubject extends Document {
  // Auto generated by mongoose
  _id: mongoose.Types.ObjectId;

  name: string;
  code: string | null;
  subjectID: string;

  lecturer: mongoose.Types.ObjectId[];
  isActive: boolean;

  students: mongoose.Types.ObjectId[];
}

export interface ICourse extends Document {
  name: string;
  code: string;
  courseID: string;

  // Legacy-ish fields used by existing UI/controller payloads
  semester?: string;
  year?: string;

  department: mongoose.Types.ObjectId;
  unit: mongoose.Types.ObjectId | null;

  lecturer: mongoose.Types.ObjectId[];
  isActive: boolean;

  studentClasses: IStudentClassMembership[];

  subjects: ICourseSubject[];

  academicYear: mongoose.Types.ObjectId;
}

const StudentClassMembershipSchema = new Schema<IStudentClassMembership>(
  {
    classID: {
      type: Schema.Types.ObjectId,
      ref: "Class",
      required: true,
    },
    students: [{ type: Schema.Types.ObjectId, ref: "User", default: [] }],
  },
  { _id: false }
);

const CourseSubjectSchema = new Schema<ICourseSubject>(
  {
    name: { type: String, required: true, trim: true },
    code: { type: String, trim: true, default: null },

    // Keep naming consistent with requested output
    subjectID: { type: String, required: true, trim: true },

    lecturer: [{ type: Schema.Types.ObjectId, ref: "User", default: [] }],
    isActive: { type: Boolean, default: true },
    students: [{ type: Schema.Types.ObjectId, ref: "User", default: [] }],
  },
  { timestamps: true }
);

const CourseSchema = new Schema<ICourse>(
  {
    name: { type: String, required: true, trim: true },
    code: { type: String, required: true, unique: true },

    courseID: { type: String, required: true, trim: true },

    semester: { type: String, required: false, trim: true, default: null },
    year: { type: String, required: false, trim: true, default: null },

    department: {
      type: Schema.Types.ObjectId,
      ref: "Department",
      required: true,
      index: true,
    },

    unit: {
      type: Schema.Types.ObjectId,
      ref: "Unit",
      required: false,
      index: true,
      default: null,
    },

    lecturer: [{ type: Schema.Types.ObjectId, ref: "User", default: [] }],
    isActive: { type: Boolean, default: true },

    // [{ classID, students: [UserIds] }]
    studentClasses: { type: [StudentClassMembershipSchema], default: [] },

    // Embedded subjects
    subjects: { type: [CourseSubjectSchema], default: [] },

    // REQUIRED: academic year
    academicYear: {
      type: Schema.Types.ObjectId,
      ref: "AcademicYear",
      required: false,
      index: true,
    },
  },
  { timestamps: true }
);

// Prevent duplicates for the same courseID + academicYear
CourseSchema.index({ courseID: 1, academicYear: 1, department: 1 }, { unique: true });

export default mongoose.model<ICourse>("Course", CourseSchema);

